# Generated by Django 4.2.30 on 2026-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("retail", "Retail Shop"),
                            ("wholesale", "Wholesale Outlet"),
                        ],
                        default="retail",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=9),
                ),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
